backend:
  name: git-gateway

# when using the default proxy server port
# local_backend: true

# when using a custom proxy server port
local_backend:
  url: http://localhost:8082/api/v1

publish_mode: editorial_workflow